import { Inter } from "next/font/google";
import "./globals.scss";
import Navbar from "./components/Navbar/Navbar";
import Footer from "./components/Footer/Footer";
import ServiceWorkerRegister from "./components/ServiceWorkerRegister/ServiceWorkerRegister";

const inter = Inter({
    variable: "--font-inter",
    subsets: ["latin"],
});

export const metadata = {
    title: "Productivity PWA",
    description: "Generated by create next app",
    manifest: "/manifest.json",
};

export const viewport = {
    themeColor: "#f4f7f7",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={`${inter.className}`}>
                <Navbar />
                {children}
                <Footer />
                <ServiceWorkerRegister />
            </body>
        </html>
    );
}
